<?php	
	include(__DIR__ . '/../head.phtml');
	$this->headScript()->prependFile($this->basePath('public/js/highscore.js'));
?>

<h3>
	Highscore
</h3>

<table class="table" id="highscore" style="width: 400px;">
	
	<thead>
		<tr>
			<th>Player</th>
			<th>Won</th>
		</tr>	
	</thead>
	
	<tbody>
		<?php foreach ($highscore as $score) : ?>
			<tr>
				<td><?php echo $this->escapeHtml($score['_id']); ?></td>			
				<td><?php echo $this->escapeHtml($score['num']); ?>x</td>
			</tr>
		<?php endforeach; ?>
	 </tbody>
	
</table>
