<?php	
	include(__DIR__ . '/../head.phtml');
?>

<h3>
	Highscore
</h3>

<table class="table" style="width: 400px;">

	<tr>
		<th>Player</th>
		<th>Won</th>
	</tr>
	
	<?php foreach ($highscore as $score) : ?>
		<tr>
			<td><?php echo $this->escapeHtml($score->winner);?></td>			
			<td><?php echo $this->escapeHtml($score->num);?>x</td>	
			
		</tr>
	<?php endforeach; ?>
	
</table>
