<?php
	include(__DIR__ . '/../head.phtml');
?>

<h3>
	<?php	
		if($game->winner == 'TIE') 
			$result = "TIE!! No winner...";
		else if(!strcmp($game->player1, $game->winner)) 
			$result = "You lost! <a href='" 
				. $this->url('game/new', array('hash' => $game->hash)) 
				. "'>Start revanche?</a>";
		else $result = "You won!";
		echo $result;
	?>
</h3>

<h4>
	Game Details:
</h4>

<table class="table">

	<tr>
		<th>Player1</th>
		<th>Player2</th>
		<th>Choice1</th>
		<th>Choice2</th>
		<th>Winner</th>
	</tr>
	<tr>	
		<td><?php echo $this->escapeHtml($game->player1);?></td>
		<td><?php echo $this->escapeHtml($game->player2);?></td>
		<td><?php echo $this->escapeHtml($game->choice1);?></td>
		<td><?php echo $this->escapeHtml($game->choice2);?></td>
		<td><?php echo $this->escapeHtml($game->winner);?></td>
	</tr>
	
</table>