<?php	
	include(__DIR__ . '/../head.phtml');
?>

<h3>
	Help
</h3>
	
<h4>
	Start a new game:
</h4>

<p>
	Under 'New Game', insert your user name and mail address (Player 1) and do so as well for the person you want to challenge (Player 2).<br />
	Be careful to insert a valid mail address, Player 2 will be notified via this address. 	
</p>

<h4>
	After having been challenged by another player:
</h4>

<p>
	Follow the link in your mail and insert your mail address to verify that you are the challenged player.<br />Choose your weapon and start the game. You will see the result of the game immediately.
</p>

<h4>
	Your closed games:
</h4>

<p>		
	You can list the results of your already competed games in 'Closed games'. You can also delete the results.
</p>
	
</p>
