<?php	
	include(__DIR__ . '/../head.phtml');
?>

<h3>
	Help
</h3>
	
<h4>
	Start a new game:
</h4>

<p>
	Under 'New Game', insert your user name and mail address (Player 1) and do so as well for the person you want to challenge (Player 2).<br />
	Be careful to insert a valid mail address, Player 2 will be notified via this address (if you check the checkbox). 	
</p>

<h4>
	After having been challenged by another player:
</h4>

<p>
	Follow the link in your mail and insert your mail address to verify that you are the challenged player.<br />Choose your weapon and start the game. You will see the result of the game immediately.<br />
	Also, your opponent will be notified via mail of the result (if you check the checkbox).
</p>


<h4>
	Revanche:
</h4>

<p>		
	If you lost, you can start a Revanche by clicking on the appearing link.<br />The information of both players will be inserted automatically in the form. You only have to choose your weapon and confirm.
</p>
	

<h4>
	Game overview:
</h4>

<p>		
	You can list your open games as well as the results of your already competed games in 'Game Overview'.
</p>
