<?php
	include(__DIR__ . '/../head.phtml');
	$this->headScript()->prependFile($this->basePath('public/js/player2game.js'));
?>

<h3>
	Player 2: <?php echo $player2; ?>
</h3>

<h4>
	Verify with your mail:
</h4>

<?php
	
	$form = $this->form;
	$form->setAttribute('action', $this->url('game/player2', array('hash' => $hash)));
	$form->prepare();

	echo $this->form()->openTag($form);
	
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('mail2'));
	echo "<div id='player2mail_error' class='error' style='display:none'>Error: Player2 Mail could not be empty!</div>";
	echo "<div id='player2mail2_error' class='error' style='display:none'>Error: Wrong Mail format! Format: test@mail.com</div>";
	
	echo "<h4>Your choice:</h4><hr />";
	
	$path = $this->basePath('public/img/game');
	echo "<div id='weapon_error' class='error' style='display:none'>Error: Choose your weapon!</div>";
?>

<div id="weapons"></div>
<div class="control-group">
	<div class="btn-group" data-toggle="buttons-radio">
		<img src="<?php echo "$path/Scissors.png"; ?>" class="btn scissors" id="3" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Spock.png"; ?>" class="btn spock" id="4" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Paper.png"; ?>" class="btn paper"id="2" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Lizard.png"; ?>" class="btn lizard" id="5" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Rock.png"; ?>" class="btn rock" id="1" onClick="reply_click(this.id)">
	</div>
</div>
	
<?php
	echo $this->formHidden($form->get('choice2'));
	
	echo "<h4>Message and Mail for Player 1:</h4><hr />";
	if(!empty($msg1)) echo "Message of Player1: '$msg1'<br /><br />";
	echo $this->formRow($form->get('msg2'));	
	echo $this->formRow($form->get('mailcheckbox'));
	
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
	
?>
