<?php
	include(__DIR__ . '/../head.phtml');	
	$this->headScript()->prependFile($this->basePath('public/js/newgame.js'));
?>

<h3>
	New game
</h3>

<?php
	
	$form = $this->form;
	$form->setAttribute('action', $this->url('game/new'));
	$form->prepare();

	echo $this->form()->openTag($form);
	
	echo "<h4>Player info:</h4><hr />";
	
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('player1'));
	echo "<div id='player1_error' class='error' style='display:none'>Error: Player1 Name could not be empty!</div>";
	echo $this->formRow($form->get('mail1'));
	echo "<div id='player1mail_error' class='error'  style='display:none'>Error: Player1 Mail could not be empty!</div>";
	echo "<div id='player1mail2_error' class='error' style='display:none'>Error: Wrong Mail format! Format: test@mail.com</div>";
	echo $this->formRow($form->get('player2'));
	echo "<div id='player2_error' class='error' style='display:none'>Error: Player2 Name could not be empty!</div>";
	echo $this->formRow($form->get('mail2'));
	echo "<div id='player2mail_error' class='error' style='display:none'>Error: Player2 Mail could not be empty!</div>";
	echo "<div id='player2mail2_error' class='error' style='display:none'>Error: Wrong Mail format! Format: test@mail.com</div>";
	
	echo "<h4>Your choice:</h4><hr />";
	
	$path = $this->basePath('public/img/game');
	echo "<div id='weapon_error' class='error' style='display:none'>Error: Choose your weapon!</div>";
?>

<div id="weapons"></div>
<div class="control-group">
	<div class="btn-group" data-toggle="buttons-radio">
		<img src="<?php echo "$path/Rock.png"; ?>" class="btn btn-primary" id="1" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Paper.png"; ?>" class="btn btn-primary" id="2" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Scissors.png"; ?>" class="btn btn-primary" id="3" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Spock.png"; ?>" class="btn btn-primary" id="4" onClick="reply_click(this.id)">
		<img src="<?php echo "$path/Lizard.png"; ?>" class="btn btn-primary" id="5" onClick="reply_click(this.id)">
	</div>
</div>
	
<?php
	echo $this->formHidden($form->get('choice1'));
	echo $this->formRow($form->get('mailcheckbox'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
?>
