<?php	
	include(__DIR__ . '/../head.phtml');
?>

<h3>
	Rules
</h3>

	<img src=" http://localhost/Zend/public/img/game.png" align="right" style="padding-right:20%;"/>

<h4>
	The game follows these rules:
</h4>
	
<p>
	<strong>The player can chose among these five weapons: </strong>
	
		<ul>
			<li>ROCK</li>
			<li>PAPER</li>
			<li>SCISSORS</li>
			<li>LIZARD</li>
			<li>SPOCK</li>
		</ul>
	
</p>

<p>		
	<strong>The rules are as follows:</strong>		
		<ul>
			<li>Scissors cut paper</li>
			<li>Paper covers rock</li>
			<li>Rock crushes lizard</li>
			<li>Lizard poisons Spock</li>
			<li>Spock smashes (or melts) scissors</li>
			<li>Scissors decapitate lizard</li>
			<li>Lizard eats paper</li>
			<li>Paper disproves Spock</li>
			<li>Spock vaporizes rock</li>
			<li>Rock breaks scissors</li>
		</ul>	
	<br />
</p>

<h4>
	Let Sheldon explain it to you: <a href="http://www.youtube.com/watch?v=iapcKVn7DdY">Youtube Video</a>
</h4>	
	
</p>
